name = "SepAI"
uid = "sepai-BHAG-AD98-8721-DABF9812741A"  
version = 1                 
description = "My first AI to learn"
author = "Sep"
url = ""  
icon = ""  
selectable = true
enabled = false
exclusive = false
ui_only = false
conflicts = {  }
before = {  }
after = {  }
hookdir = 'hook'
